language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

script: ./gradlew build checkstyle -Dorg.gradle.daemon=false

deploy:
  provider: releases
  api_key:
    secure: "yGxO4NkiTO5faA+4EWERPufi8NRlSKiOZxgk3HqLISG3LBHI5UcBCbdDPUhB5O5cw47wG3BZlX4B8SPP4jMWtAmwAify6FcxtatFGzpKy8Z2CBRo68BHIYj4vtnyQ2VcQpt4sn5rJLY6wJkcHk3piYp99aAhafT1KfjYthLF9YVEDm2VMMSg4o1X5Lf1Bj5PZy5VOx+RuBTCGvPUNT6DHXafYr36x8kkQRLD/W6xst3GcqzGy+WJJXHIKcORi8walx6ER6vrTkxhJ/LyzMKh9EbdpK+t/Bz4HywvYZKFIpfjJxFJ+35knXcmHDmpXeID86apC8duYJm5BsHCUBi+WzSewLntf+5sb81PyP1Ej1pUJO6fjyTxM0LCUs6J/AIxWpiM0JVXNLZMg6A1JW/purHvUmYco06Gjq17ic48vDMXNSa8NnyqIbMti/rGE3Ou5t/MXPybrQlTeRXZOiE1hgjBkDGgpOvQCM74TKI1nXb0jIl0ia1ALrzIfqGnHb43QJKqHkygKnWmQvwQogqtxMCt0RD3OaekHpBAcpC8cj+hhycURHyXxUJWQSCss0UZYOVVU4KTAe8w6OuUy8I2RIH6QLXHskK8sev2BY3wsDSoCvaUzmkmoPCqZEf7T2uGJAvJtsDVQTKEugorSvmQ1fFK7d/Zg9n0wxNQ+mlGAUU="
  skip_cleanup: true
  file_glob: true
  file: "build/libs/*.jar"
  on:
    tags: true
    jdk: oraclejdk8
    repo: natrolite/vault

branches:
  except:
    - gh-pages

notifications:
  email: false